quarkus.redis.hosts=${QUARKUS_REDIS_HOSTS:redis://localhost:6379}

quarkus.grpc.server.port=9000
quarkus.grpc.server.enable-reflection-service=true
quarkus.grpc.server.use-separate-server=true

ratelimit.window-seconds=${RATELIMIT_WINDOW_SECONDS:60}

ratelimit.gold-limit=${GOLD_LIMIT:30}
ratelimit.silver-limit=${SILVER_LIMIT:15}
ratelimit.free-limit=${FREE_LIMIT:5}