quarkus.redis.hosts=${QUARKUS_REDIS_HOSTS:redis://localhost:6379}

quarkus.grpc.server.port=9000

quarkus.grpc.server.enable-reflection-service=true

quarkus.grpc.server.use-separate-server=true

ratelimit.window.ms=60000

ratelimit.max.requests=4