mp.messaging.incoming.input-topic.connector=smallrye-kafka
mp.messaging.incoming.input-topic.topic=input-topic
mp.messaging.incoming.input-topic.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.input-topic.bootstrap.servers=my-kafka-kafka-bootstrap.kafka.svc:9092

mp.messaging.outgoing.output-topic.connector=smallrye-kafka
mp.messaging.outgoing.output-topic.topic=output-topic
mp.messaging.outgoing.output-topic.value.serializer=org.apache.kafka.common.serialization.StringSerializer
mp.messaging.outgoing.output-topic.bootstrap.servers=my-kafka-kafka-bootstrap.kafka.svc:9092